### ISSUE TITLE
Upgrade opencv library to be compilable on ROS Melodic

### ISSUE THREAD

**Issue by lvanasse** [clubcapra/capra_motion_detection_ros#1]
opencv3 doesn't have a package under ROS Melodic, so the node needs to have its library update.

**Comment by lit-af** [comment]
@Ludoenso Can this issue be closed?

**Comment by lvanasse** [comment]
Well, @MaDumont is working on the hector_vision node. Since he's testing it on Kinetic, we still don't know if we need to upgrade the library. I'd keep it open until we are certain that we don't need to update it, either since the hector_vision node works on Melodic or that we update our node with the OpenCV that will need to be compiled manually.

**Comment by MaDumont** [comment]
https://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html for compilling opencv.
